### PR TITLE
add Separator Component

### PR DESCRIPTION
**Pull request by juauz**
screen shot 2018-06-15 at 10 48 38

### CODE REVIEW

**Comment by juauz** [comment]
@joaojusto what is missing for the build to go green?

**Comment by fmmricardo** [comment]
@juauz  did you solved the issue? 
on Pages/index.js? 

here is the conflit : 
<<<<<<< ja-separators
import Separator from '../Components/Separator';
=======
import Layout from './Layout';
import Footer from '../Components/Footer';
>>>>>>> master

**Comment by juauz** [comment]
@joaojusto @fmmricardo can't understand what is going wrong.

**Comment by fmmricardo** [comment]
@juauz i fixed the extra div thar i found on Pages/index.js file but ther actually 11 things to fix. 

1:15  error  A space is required after '{'                             object-curly-spacing
  1:25  error  A space is required before '}'                            object-curly-spacing
  5:1   error  Expected indentation of 2 spaces but found 4              indent
  6:1   error  Expected indentation of 4 spaces but found 8              indent
  6:16  error  Missing parentheses around multilines JSX                 react/jsx-wrap-multilines
  7:13  error  Expected indentation of 10 space characters but found 12  react/jsx-indent
  7:57  error  'children' is missing in props validation                 react/prop-types
  8:9   error  Expected closing tag to match indentation of opening      react/jsx-closing-tag-location
  8:15  error  Missing semicolon                                         semi
  9:1   error  Expected indentation of 2 spaces but found 4              indent

/home/runner/publishing-platform/src/pages/index.js
  50:11  error  A space is required before closing bracket  react/jsx-tag-spacing

**Comment by fmmricardo** [comment]
@juauz  agora é que está. green

**Pull request merged**
